### PR TITLE
Filter out email addresses in responses

### PR DESCRIPTION
**Pull request by BugBountyzip**
### Bambda Contributions

* [ ] Bambda has a valid [header](https://github.com/PortSwigger/bambdas/blob/73077e7ff3f6fac9db7dc95c0a00bd842b6bb64c/Proxy/HTTP/FilterOnCookieValue.bambda#L1-L5), featuring an `@author` annotation and suitable description
* [ ] Bambda compiles and executes as expected
* [ ] Only .bambda files have been added or modified (README.md files are automatically updated / generated after PR merge)

### CODE REVIEW

**Comment by BugBountyzip** [comment]
Thank you for the update. I understand how busy schedules can be, and I appreciate your attention to the review process. Please take the time you need to provide feedback on the pull requests. I'm here to assist with any further clarifications or adjustments as required once you've had the chance to review them.

Looking forward to your feedback. Have a great week!

**Review by PortSwiggerWiener — APPROVED** [review]
Thanks for your patience during the review process.

Looks good 👍

**Comment by BugBountyzip** [comment]
Thank you for the opportunity to contribute here. I'm proud to announce that I've become the #1 contributor on this GitHub repository. 

Looking forward to sharing more in the future.

**Review by ps-porpoise — APPROVED** [review]
👍 Looks good.

**Pull request merged**
