### PR TITLE
Create MultiFilter.bambda

### PR DESCRIPTION
**Pull request by BugBountyzip**
I just made this new MultiFilter

### Bambda Contributions

* [x] Bambda has a valid [header](https://github.com/PortSwigger/bambdas/blob/73077e7ff3f6fac9db7dc95c0a00bd842b6bb64c/Proxy/HTTP/FilterOnCookieValue.bambda#L1-L5), featuring an `@author` annotation and suitable description
* [x] Bambda compiles and executes as expected
* [x] Only .bambda files have been added or modified (README.md files are automatically updated / generated after PR merge)

🌐 Introducing the "Multi Filter Bambda for Burp Suite" - a game-changer for both Community and Professional users! Streamline your HTTP history analysis with user-defined filters.

✅ Custom filters for host, path, status code, & more.
⚡️ Compatible with Burp Suite Community & Professional editions.
💡 Find precise data in seconds, not minutes

### CODE REVIEW

**Comment by BugBountyzip** [comment]
⚡ Don't Stay Behind - Adopt the Multi Filter Bambda and revolutionize the way you interact with your HTTP history in Burp Suite! ⚡

🔍 Dynamic User-Defined Filters Include:

    hostFilter: Target entries by host.
    pathFilter: Find specific paths within URLs.
    statusCodeFilter: Filter responses by status code.
    methodFilter: Select HTTP methods like GET or POST.
    requestBodyFilter: Search within the content of request bodies.
    responseBodyFilter: Filter responses based on their body content.
    mimeTypeFilter: Look for specific MIME types.
    notesFilter: Filter entries based on notes content.

By not leveraging the power of Bambdas, you're missing out on optimizing your security testing processes. This Bambda is your key to unlocking a more effective and streamlined approach to sifting through HTTP history.

🔥 Start Using the Multi Filter Bambda Now!
Transform your Burp Suite experience and make your web security testing more productive and less time-consuming.

**Comment by ps-porpoise** [comment]
Hey @BugBountyzip, thanks for your submission!

After reviewing your Bambda submission, we have the following feedback:
- Whilst your Bambda is very comprehensive, we feel that this bambda is too generic, and doesn't add much additional functionality over the original "Settings mode" view.
- The large amount of comments makes this difficult to use and modify at a glance - whilst comments can be a useful tool, making your code easy to read by using descriptive variables and formatting is more effective.
- We noticed that if an item does not have any notes, this Bambda will return false, regardless of the user-defined criteria.

For these reasons, unfortunately we won't be accepting this pull request, but we look forward to any future contributions!

**Comment by BugBountyzip** [comment]
Hello @ps-porpoise  

I wanted to thank you for your feedback on my recent Bambda submission. I truly appreciate the time and effort you put into reviewing it.

Regarding your comments, I wanted to highlight a few points:

- >  The extensive comments were added to ensure clarity, but I understand they might be overwhelming. I can easily streamline the code by reducing or removing these comments.

- >  I noticed the issue you mentioned where the Bambda returns false if an item lacks notes. I can quickly fix this bug, or alternatively, I can remove the notes function entirely, especially since I've already provided this functionality in a separate approved bambad.

- > One of the key strengths of this Bambda is its ability to write queries matching multiple conditions simultaneously, which I believe adds significant value to the project.


Previous Generic Submissions: I understand the concern about the submission being too generic. However, I’ve observed similar, if not more generic, contributions being accepted in the past. If there's a change in the project's direction or criteria for contributions, I'd love to understand more.

I deeply value the opportunity to contribute to this project and the support you've provided throughout my time here. 
Thank you once again for the opportunity to be a part of this project. It’s been a rewarding experience contributing and learning alongside such a talented team.

Bye ;)

**Comment by PortSwiggerWiener** [comment]
@BugBountyzip Please don't let this one PR discourage you from making further contributions! We would love to see more submissions from you in the future. This repository is very much a partnership between us all.

**Pull request closed without merging**
