### PR TITLE
Bambda Script to Filter on a Specific Highlight Color

### PR DESCRIPTION
**Pull request by ncoblentz**
### Bambda Contributions

* [ ] Bambda has a valid [header](https://github.com/PortSwigger/bambdas/blob/73077e7ff3f6fac9db7dc95c0a00bd842b6bb64c/Proxy/HTTP/FilterOnCookieValue.bambda#L1-L5), featuring an @author annotation and suitable description
* [ ] Bambda is in the correct directory
* [ ] Bambda compiles and executes as expected

### CODE REVIEW

**Comment by PortSwiggerWiener** [comment]
Thanks for the submission! It looks good, but can you revert the changes to the README.md as this will be updated automatically once the PR is merged. I'll update the docs to make this clear as I appreciate that this isn't at all obvious!

If you want to see what the markdown will look like and tweak your bambda then if you run `java -jar BambaChecker.jar` from the root of your repo then it will update your local copy.

**Review by PortSwiggerWiener — APPROVED** [review]
Looks good 👍

**Comment by ncoblentz** [comment]
Changes made! Thanks for the tip about BambaChecker! It's ready for another review.

**Comment by ncoblentz** [comment]
Side note, the "author" field in my JavaDoc is markdown syntax and that made it through to the README.md as a valid clickable link. Just wanted to point that out in case that's not how you want that to work.

**Review by Hannah-PortSwigger — APPROVED** [review]
Looks good 👍

**Comment by Hannah-PortSwigger** [comment]
Thanks for the heads up on the link - we'll discuss this further tomorrow and then either conclude the merge or request the link be removed.

We'll also add some additional info to the submission guidelines around our stance on links as well.

**Pull request merged**
