### PR TITLE
feat: bambda for pwnfox housekeeping

### PR DESCRIPTION
**Pull request by GangGreenTemperTatum**
### Bambda Contributions

* [x] Bambda has a valid [header](https://github.com/PortSwigger/bambdas/blob/73077e7ff3f6fac9db7dc95c0a00bd842b6bb64c/Proxy/HTTP/FilterOnCookieValue.bambda#L1-L5), featuring an `@author` annotation and suitable description
* [x] Bambda compiles and executes as expected
* [x] Only .bambda files have been added or modified (README.md files are automatically updated / generated after PR merge)

### CODE REVIEW

**Review by Hannah-PortSwigger — COMMENTED** [review]
Could this be simplified to the following?
```java
return request.isInScope() && request.hasHeader("X-Pwnfox-Color");
```

If you were interested, you could also add color highlighting to this Bambda.

**Comment by GangGreenTemperTatum** [comment]
> Could this be simplified to the following?
> 
> ```java
> return request.isInScope() && request.hasHeader("X-Pwnfox-Color");
> ```

good feedback, thanks for the sloppiness. - [addressed](https://github.com/PortSwigger/bambdas/pull/80/commits/2749267b9689a97bc0bfdd3ade0f7a6028889afb) and tested

pwnfox supports the following color schemas:

image

> If you were interested, you could also add color highlighting to this Bambda.
i think this would make more sense if you were using FoxyProxy or something similar? although looking there doesn't seem to be inherited user-agent headers that distinguish it.. Effectively using something like FoxyProxy and the suggested bambda you could re-create pwnfox in an alternate engineering way.. hope that makes sense

**Comment by Hannah-PortSwigger** [comment]
Thanks for making this change! This looks good :)

I was having a look at [this reference on the PwnFox repo](https://github.com/yeswehack/PwnFox?tab=readme-ov-file#containers-profiles) but after a closer read it does sound more in-depth than would be achievable with a Bambda.

**Review by Hannah-PortSwigger — APPROVED** [review]

**Comment by GangGreenTemperTatum** [comment]
> Thanks for making this change! This looks good :)
> 
> I was having a look at [this reference on the PwnFox repo](https://github.com/yeswehack/PwnFox?tab=readme-ov-file#containers-profiles) but after a closer read it does sound more in-depth than would be achievable with a Bambda.

agreed, thanks for the approval! :)

**Review by ps-porpoise — APPROVED** [review]
Looks good!

**Pull request merged**
